Upgrade to newer discord.js to fix crippling problem that just started happening after running without issue for almost a year
This problem just appeared on it's own (nothing had changed in the app or the server it was running on). Whenever an interaction occured, the bot would throw this exception and exit:

```
        if (channel && !channel.isTextBased()) return;
                                ^

TypeError: channel.isTextBased is not a function
```

References:
* https://stackoverflow.com/questions/75892478/discord-js-v14-7-1-typeerror-channel-istextbased-is-not-a-function
* https://github.com/discordjs/discord.js/issues/9295